package org.l4cs.pl.syntax;

import static org.l4cs.pl.syntax.Formula.FormulaKind.AND;
import static org.l4cs.pl.syntax.Formula.FormulaKind.IMPLIES;
import static org.l4cs.pl.syntax.Formula.FormulaKind.NOT;
import static org.l4cs.pl.syntax.Formula.FormulaKind.OR;
import static org.l4cs.pl.syntax.Formula.FormulaKind.PROP;

import java.io.PrintStream;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

import org.l4cs.util.TextUtil;

/**
 * This class supports Propositional Logic formulas and basic operations on
 * them.
 * 
 * @author Stephen Siegel
 */
public class FormulaFactory {

	/**
	 * Where the verbose output will go.
	 */
	protected final static PrintStream out = System.out, err = System.err;

	// Fields...

	private False falseFormula = new False();

	private Formula trueFormula = not(falseFormula);

	/**
	 * Flyweight Pattern for Propositions. Every proposition ever requested has an
	 * entry in this map, which maps the proposition's unique ID number to the
	 * unique instance of {@link Proposition} with that ID.
	 */
	private Map<Integer, Proposition> idMap = new HashMap<>();

	/**
	 * Map from proposition names to propositions. Every proposition has a name,
	 * unique within this factory. The name of a proposition must be a non-null
	 * String.
	 */
	private Map<String, Proposition> nameMap = new HashMap<>();

	/**
	 * The maximum ID of a proposition created by this factory.
	 */
	private int idMax = -1;

	/**
	 * The maximum suffix used for "fresh" propositions. A fresh proposition is one
	 * with name of the form "p"+i, for a nonnegative int i. Names of this form are
	 * used when the client requests a "fresh" proposition (one that has not been
	 * seen before). The client wants this factory to come up with a unique name.
	 * The factory keeps track of the maximum i seen, so will increment that to
	 * yield i and a fresh name "p"+i.
	 */
	private int freshMax = -1;

	/**
	 * An object used to convert formulas to conjunctive normal form.
	 */
	private CnfConverter cnfConverter = new CnfConverter(this);

	/**
	 * An object used to convert formulas to disjunctive normal form.
	 */
	private DnfConverter dnfConverter = new DnfConverter(this);

	// Constructor...

	public FormulaFactory() {
	}

	// Formula creation methods ...

	/**
	 * Returns the proposition with this name. There is at most one instance of
	 * {@link Proposition} generated by this factory with a given name. If that
	 * proposition already exists, it is returned. Otherwise, a new proposition is
	 * created and given the name.
	 * 
	 * @param name the name of the proposition
	 * @return the proposition with name {@code name}
	 */
	public Proposition proposition(String name) {
		Proposition q = nameMap.get(name);
		if (q == null) {
			int id = ++idMax;
			q = new Proposition(id, name);
			nameMap.put(name, q);
			idMap.put(id, q);
			if (name.startsWith("p")) {
				String suffix = name.substring(1);
				try {
					int freshId = Integer.parseUnsignedInt(suffix);
					if (freshId > freshMax)
						freshMax = freshId;
				} catch (NumberFormatException e) {
					// not a fresh name, do nothing
				}
			}
		}
		return q;
	}

	/**
	 * Returns a proposition that has never been returned before by this factory,
	 * and which has a name that has never been used before.
	 * 
	 * @return a fresh proposition
	 */
	public Proposition freshProposition() {
		int id = ++idMax;
		int fid = ++freshMax;
		String name = "p" + fid;
		Proposition p = new Proposition(id, name);
		nameMap.put(name, p);
		idMap.put(id, p);
		return p;
	}

	public False falseFormula() {
		return falseFormula;
	}

	public Formula trueFormula() {
		return trueFormula;
	}

	public NotFormula not(Formula arg) {
		return new NotFormula(arg);
	}

	public BinaryFormula and(Formula arg0, Formula arg1) {
		return new BinaryFormula(AND, arg0, arg1);
	}

	public BinaryFormula or(Formula arg0, Formula arg1) {
		return new BinaryFormula(OR, arg0, arg1);
	}

	public BinaryFormula implies(Formula arg0, Formula arg1) {
		return new BinaryFormula(IMPLIES, arg0, arg1);
	}

	/**
	 * A<->B is shorthand for (A->B) & (B->A).
	 */
	public BinaryFormula iff(Formula arg0, Formula arg1) {
		return and(implies(arg0, arg1), implies(arg1, arg0));
	}

	// Formula getters ...

	/**
	 * Gets the proposition with the given ID.
	 * 
	 * @param id ID number of a proposition; must be a nonnegative int
	 * @return the proposition with ID {@code id}, or {@code null} if there is none.
	 */
	public Proposition getProposition(int id) {
		return idMap.get(id);
	}

	public boolean isTrue(Formula a) {
		return trueFormula.equals(a);
	}

	public boolean isFalse(Formula a) {
		return falseFormula.equals(a);
	}

	public boolean isProp(Formula a) {
		return a.kind() == PROP;
	}

	public boolean isNot(Formula a) {
		return a.kind() == NOT;
	}

	public boolean isBinary(Formula a) {
		return a instanceof BinaryFormula;
	}

	public boolean isAnd(Formula a) {
		return a.kind() == AND;
	}

	public boolean isOr(Formula a) {
		return a.kind() == OR;
	}

	public boolean isImplies(Formula a) {
		return a.kind() == IMPLIES;
	}

	/**
	 * Returns the ID of a Proposition.
	 * 
	 * @param a a proposition
	 * @return the ID number of the proposition
	 */
	public int id(Formula a) {
		return ((Proposition) a).id();
	}

	/**
	 * Returns arg0 of a binary formula, i.e., the left argument.
	 * 
	 * @param a an instance of BinaryFormula
	 * @return arg0 of the binary formula
	 */
	public Formula arg0(Formula a) {
		assert isBinary(a);
		return ((BinaryFormula) a).arg0();
	}

	/**
	 * Returns arg1 of a binary formula, i.e., the right argument.
	 * 
	 * @param a an instance of BinaryFormula
	 * @return arg1 of the binary formula
	 */
	public Formula arg1(Formula a) {
		assert isBinary(a);
		return ((BinaryFormula) a).arg1();
	}

	/**
	 * Returns the argument of a NotFormula a.
	 * 
	 * @param a an instance of NotFormula
	 * @return the arg of the NotFormula
	 */
	public Formula arg(Formula a) {
		assert isNot(a);
		return ((NotFormula) a).arg();
	}

	/**
	 * Is formula a a literal, i.e., either a proposition or NOT a proposition.
	 * 
	 * @param a any formula
	 * @return true iff a is a literal
	 */
	public boolean isLiteral(Formula a) {
		return isProp(a) || (isNot(a) && isProp(arg(a)));
	}

	private void varsAux(Formula a, Set<Proposition> set) {
		if (isProp(a))
			set.add((Proposition) a);
		else if (isNot(a)) {
			varsAux(arg(a), set);
		} else if (isBinary(a)) {
			varsAux(arg0(a), set);
			varsAux(arg1(a), set);
		}
	}

	public Set<Proposition> vars(Formula a) {
		Set<Proposition> result = new HashSet<>();
		varsAux(a, result);
		return result;
	}

	// NNF (Negation Normal Form) ...

	/**
	 * Determines whether a formula is in negation normal form. In NNF, the the
	 * IMPLIES operator cannot occur, and NOT can occur only immediately before
	 * FALSE or a proposition.
	 * 
	 * @param a a formula
	 * @return true iff a is in NNF
	 */
	public boolean isNnf(Formula a) {
		switch (a.kind()) {
		case AND:
		case OR:
			return isNnf(arg0(a)) && isNnf(arg1(a));
		case FALSE:
		case PROP:
			return true;
		case IMPLIES:
			return false;
		case NOT:
			return isFalse(arg(a)) || isProp(arg(a));
		default:
			throw new RuntimeException("unreachable");
		}
	}

	/**
	 * Converts a formula to an equivalent NNF formula in linear time.
	 * 
	 * @param a a formula
	 * @return an equivalent formula in NNF
	 */
	public Formula nnf(Formula a) {
		switch (a.kind()) {
		case FALSE:
		case PROP:
			return a;
		case AND:
			return and(nnf(arg0(a)), nnf(arg1(a)));
		case OR:
			return or(nnf(arg0(a)), nnf(arg1(a)));
		case IMPLIES:
			return or(nnf(not(arg0(a))), nnf(arg1(a)));
		case NOT:
			Formula b = arg(a);
			switch (b.kind()) {
			case FALSE:
			case PROP:
				return a;
			case NOT:
				return nnf(arg(b));
			case AND:
				return or(nnf(not(arg0(b))), nnf(not(arg1(b))));
			case OR:
				return and(nnf(not(arg0(b))), nnf(not(arg1(b))));
			case IMPLIES:
				return and(nnf(arg0(b)), nnf(not(arg1(b))));
			default:
				throw new RuntimeException("unreachable");
			}
		default:
			throw new RuntimeException("unreachable");
		}
	}

	public Formula nnfv(String pre, Formula a) {
		Formula result;
		String newpre = pre + "  | ";
		err.print(pre + "nnf(" + a + ") = ");
		switch (a.kind()) {
		case FALSE:
		case PROP:
			err.println(a);
			return a;
		case AND: {
			err.println("nnf(" + arg0(a) + ") " + TextUtil.and() + " nnf(" + arg1(a) + ")");
			result = and(nnfv(newpre, arg0(a)), nnfv(newpre, arg1(a)));
			break;
		}
		case OR: {
			err.println("nnf(" + arg0(a) + ") " + TextUtil.or() + " nnf(" + arg1(a) + ")");
			result = or(nnfv(pre + "  | ", arg0(a)), nnfv(newpre, arg1(a)));
			break;
		}
		case IMPLIES: {
			err.println("nnf(" + not(arg0(a)) + ") " + TextUtil.or() + " nnf(" + arg1(a) + ")");
			result = and(nnfv(pre + "  | ", not(arg0(a))), nnfv(newpre, arg1(a)));
			break;
		}
		case NOT:
			Formula b = arg(a);
			switch (b.kind()) {
			case FALSE:
			case PROP:
				err.println(a);
				return a;
			case NOT: {
				err.println("nnf(" + arg(b) + ")");
				result = nnfv(newpre, arg(b));
				break;
			}
			case AND: {
				err.println("nnf(" + not(arg0(b)) + ") " + TextUtil.or() + " nnf(" + not(arg1(b)) + ")");
				result = or(nnfv(newpre, not(arg0(b))), nnfv(newpre, not(arg1(b))));
				break;
			}
			case OR: {
				err.println("nnf(" + not(arg0(b)) + ") " + TextUtil.and() + " nnf(" + not(arg1(b)) + ")");
				result = and(nnfv(newpre, not(arg0(b))), nnfv(newpre, not(arg1(b))));
				break;
			}
			case IMPLIES: {
				err.println("nnf(" + arg0(b) + ") " + TextUtil.and() + " nnf(" + not(arg1(b)) + ")");
				result = and(nnfv(newpre, arg0(b)), nnfv(newpre, not(arg1(b))));
				break;
			}
			default:
				throw new RuntimeException("unreachable");
			}
			break;
		default:
			throw new RuntimeException("unreachable");
		}
		err.println(pre + "= " + result);
		return result;
	}

	/**
	 * Given a literal a, return \bar{a}. If a is a proposition, returns a, if a is
	 * !p, returns p.
	 * 
	 * @param a a literal
	 * @return bar(a)
	 */
	public Formula bar(Formula a) {
		return isProp(a) ? not(a) : arg(a);
	}

	// CNF (Conjunctive Normal Form) ...

	/**
	 * Is the given formula a disjunction of 1 or more literals?
	 * 
	 * @param a any formula
	 * @return true iff a is a literal or it is the (right associated) disjunction
	 *         of two or more literals
	 */
	private boolean isLiteralDisjunction(Formula a) {
		return (isOr(a) && isLiteral(arg0(a)) && isLiteralDisjunction(arg1(a))) || isLiteral(a);
	}

	/**
	 * Is the given formula a CNF clause?
	 * 
	 * @param a any formula
	 * @return true iff a is false, a literal, or a rightly-associative disjunction
	 *         of 2 or more literals.
	 */
	public boolean isCnfClause(Formula a) {
		return isFalse(a) || isLiteralDisjunction(a);
	}

	/**
	 * Is the given formula a (right-associated) conjunction of 1 or more CNF
	 * clauses?
	 * 
	 * @param a any formula
	 * @return true iff a is a CNF clause or is the conjunction of two or more CNF
	 *         clauses
	 */
	private boolean isCnfClauseConjunction(Formula a) {
		return (isAnd(a) && isCnfClause(arg0(a)) && isCnfClauseConjunction(arg1(a))) || isCnfClause(a);
	}

	/**
	 * Is the given formula in CNF?
	 * 
	 * @param a a formula
	 * @return true iff a is the true formula, a single CNF clause, or a
	 *         rightly-associative conjunction of 2 or more CNF clauses.
	 */
	public boolean isCnf(Formula a) {
		return isTrue(a) || isCnfClauseConjunction(a);
	}

	/**
	 * Returns an iterator over the clauses of the CNF formula. For the "true"
	 * formula, this will be an empty iterator.
	 * 
	 * @param cnf a CNF formula
	 * @return iterator over clauses
	 */
	public Iterator<Formula> cnfClauseIterator(Formula cnf) {
		return cnfConverter.cnfClauseIterator(cnf);
	}

	/**
	 * Returns an iterator over the literals of a CNF clause. For the "false"
	 * clause, this will be an empty iterator.
	 * 
	 * @param cnfClause a CNF clause (disjunction of literals or false)
	 * @return iterator over the literals
	 */
	public Iterator<Formula> cnfLiteralIterator(Formula cnfClause) {
		return cnfConverter.cnfLiteralIterator(cnfClause);
	}

	/**
	 * Converts any formula to an equivalent CNF formula.
	 * 
	 * @param a a formula
	 * @return a CNF formula equivalent to {@code a}
	 */
	public Formula cnf(Formula a) {
		return cnfConverter.cnf(a);
	}

	// DNF (Disjunctive Normal Form) ...

	/**
	 * Is the given formula a conjunction of 1 or more literals?
	 * 
	 * @param a any formula
	 * @return true iff a is a literal or it is the (right associated) conjunction
	 *         of two or more literals
	 */
	private boolean isLiteralConjunction(Formula a) {
		return (isAnd(a) && isLiteral(arg0(a)) && isLiteralConjunction(arg1(a))) || isLiteral(a);
	}

	/**
	 * Is the given formula a DNF clause?
	 * 
	 * @param a any formula
	 * @return true iff a is true, a literal, or a rightly-associative conjunction
	 *         of 2 or more literals.
	 */
	public boolean isDnfClause(Formula a) {
		return isTrue(a) || isLiteralConjunction(a);
	}

	/**
	 * Is the given formula a (right-associated) disjunction of 1 or more DNF
	 * clauses?
	 * 
	 * @param a any formula
	 * @return true iff a is a DNF clause or is the disjunction of two or more DNF
	 *         clauses
	 */
	private boolean isDnfClauseDisjunction(Formula a) {
		return (isOr(a) && isDnfClause(arg0(a)) && isDnfClauseDisjunction(arg1(a))) || isDnfClause(a);
	}

	/**
	 * Is the given formula in DNF?
	 * 
	 * @param a a formula
	 * @return true iff a is the false formula, a single DNF clause, or a
	 *         rightly-associative disjunction of 2 or more DNF clauses.
	 */
	public boolean isDnf(Formula a) {
		return isFalse(a) || isDnfClauseDisjunction(a);
	}

	/**
	 * Returns an iterator over the clauses of the DNF formula. For the "false"
	 * formula, this will be an empty iterator.
	 * 
	 * @param dnf a DNF formula
	 * @return iterator over clauses
	 */
	public Iterator<Formula> dnfClauseIterator(Formula dnf) {
		return dnfConverter.dnfClauseIterator(dnf);
	}

	/**
	 * Returns an iterator over the literals of a DNF clause. For the "true" clause,
	 * this will be an empty iterator.
	 * 
	 * @param dnfClause a DNF clause (conjunction of literals or true)
	 * @return iterator over the literals
	 */
	public Iterator<Formula> dnfLiteralIterator(Formula dnfClause) {
		return dnfConverter.dnfLiteralIterator(dnfClause);
	}

	/**
	 * Converts any formula to an equivalent DNF formula.
	 * 
	 * @param a a formula
	 * @return a DNF formula equivalent to {@code a}
	 */
	public Formula dnf(Formula a) {
		return dnfConverter.dnf(a);
	}

	// Tseytin's algorithm...

	/**
	 * Converts any formula to an equisatisfiable CNF formula using Tseytin's
	 * algorithm.
	 */
	public Formula tseytin(Formula a) {
		Tseytin t = new Tseytin();
		Formula result = t.compute(a);
		for (Formula clause : t.clauses)
			result = and(clause, result);
		return result;
	}

	class Tseytin {

		/**
		 * The set to which newly generated clauses should be added.
		 */
		Set<Formula> clauses = new HashSet<>();

		/**
		 * Performs Tseytin on f, introducing new propositions, constructing the new
		 * auxiliary CNF clauses, and returning the literal associated to f.
		 * 
		 * @param f      any formula, to be converted to equisatisfiable CNF
		 * @param maxPid the current maximum ID number of a proposition occurring in f
		 *               or clauses
		 * @return the literal representing f
		 */
		Formula compute(Formula f) {
			switch (f.kind()) {
			case AND: {
				// {{x,!y,!z},{!x,y},{!x,z}}
				Formula y = compute(arg0(f)), z = compute(arg1(f));
				Proposition x = freshProposition();
				clauses.add(or(x, or(bar(y), bar(z))));
				clauses.add(or(bar(x), y));
				clauses.add(or(bar(x), z));
				return x;
			}
			case FALSE: {
				Proposition x = freshProposition();
				clauses.add(not(x));
				return x;
			}
			case IMPLIES: {
				// {{x,y},{x,!z},{!x,!y,z}}
				Formula y = compute(arg0(f)), z = compute(arg1(f));
				Proposition x = freshProposition();
				clauses.add(or(x, y));
				clauses.add(or(x, bar(z)));
				clauses.add(or(not(x), or(bar(y), z)));
				return x;
			}
			case NOT: {
				Formula x = compute(arg(f));
				return bar(x);
			}
			case OR: {
				// {{x,!y},{x,!z},{!x,y,z}}
				Formula y = compute(arg0(f)), z = compute(arg1(f));
				Proposition x = freshProposition();
				clauses.add(or(x, bar(y)));
				clauses.add(or(x, bar(z)));
				clauses.add(or(not(x), or(y, z)));
				return x;
			}
			case PROP:
				return f;
			default:
				throw new RuntimeException("unreachable");
			}
		}
	}
}
